package app.semblance.ui.wizard

data class DevicePreset(
    val id: String,
    val name: String,
    val model: String,
    val brand: String,
    val androidVersion: Int,
    val chromeVersion: Int,
    val screenWidth: Int,
    val screenHeight: Int,
    val screenDensity: Float,
    val gpu: String,
    val cores: Int,
    val ramGb: Int,
    val tlsId: String,
    val userAgent: String,
    val clientHintsPlatform: String,
    val clientHintsPlatformVersion: String,
    val clientHintsModel: String
)

object DeviceLibrary {
    val presets: List<DevicePreset> = listOf(
        DevicePreset(
            id = "pixel_7_pro",
            name = "Google Pixel 7 Pro (Cheetah)",
            model = "Pixel 7 Pro",
            brand = "Google",
            androidVersion = 14,
            chromeVersion = 124,
            screenWidth = 1440,
            screenHeight = 3120,
            screenDensity = 3.5f,
            gpu = "Mali-G710",
            cores = 8,
            ramGb = 12,
            tlsId = "HelloChrome_124",
            userAgent = "Mozilla/5.0 (Linux; Android 14; Pixel 7 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36",
            clientHintsPlatform = "Android",
            clientHintsPlatformVersion = "14.0.0",
            clientHintsModel = "Pixel 7 Pro"
        ),
        DevicePreset(
            id = "galaxy_s23",
            name = "Samsung Galaxy S23 (Kalama)",
            model = "SM-S911B",
            brand = "Samsung",
            androidVersion = 14,
            chromeVersion = 123,
            screenWidth = 1080,
            screenHeight = 2340,
            screenDensity = 3.0f,
            gpu = "Adreno 740",
            cores = 8,
            ramGb = 8,
            tlsId = "HelloChrome_123",
            userAgent = "Mozilla/5.0 (Linux; Android 14; SM-S911B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36",
            clientHintsPlatform = "Android",
            clientHintsPlatformVersion = "14.0.0",
            clientHintsModel = "SM-S911B"
        ),
        DevicePreset(
            id = "pixel_6a",
            name = "Google Pixel 6a (Bluejay)",
            model = "Pixel 6a",
            brand = "Google",
            androidVersion = 14,
            chromeVersion = 124,
            screenWidth = 1080,
            screenHeight = 2400,
            screenDensity = 2.625f,
            gpu = "Mali-G78",
            cores = 8,
            ramGb = 6,
            tlsId = "HelloChrome_124",
            userAgent = "Mozilla/5.0 (Linux; Android 14; Pixel 6a) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36",
            clientHintsPlatform = "Android",
            clientHintsPlatformVersion = "14.0.0",
            clientHintsModel = "Pixel 6a"
        ),
        DevicePreset(
            id = "oneplus_11",
            name = "OnePlus 11 5G",
            model = "CPH2449",
            brand = "OnePlus",
            androidVersion = 13,
            chromeVersion = 122,
            screenWidth = 1440,
            screenHeight = 3216,
            screenDensity = 3.5f,
            gpu = "Adreno 740",
            cores = 8,
            ramGb = 16,
            tlsId = "HelloChrome_122",
            userAgent = "Mozilla/5.0 (Linux; Android 13; CPH2449) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36",
            clientHintsPlatform = "Android",
            clientHintsPlatformVersion = "13.0.0",
            clientHintsModel = "CPH2449"
        ),
        DevicePreset(
            id = "xiaomi_13",
            name = "Xiaomi 13 (Fuxi)",
            model = "2211133C",
            brand = "Xiaomi",
            androidVersion = 14,
            chromeVersion = 124,
            screenWidth = 1080,
            screenHeight = 2400,
            screenDensity = 3.0f,
            gpu = "Adreno 740",
            cores = 8,
            ramGb = 12,
            tlsId = "HelloChrome_124",
            userAgent = "Mozilla/5.0 (Linux; Android 14; 2211133C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36",
            clientHintsPlatform = "Android",
            clientHintsPlatformVersion = "14.0.0",
            clientHintsModel = "2211133C"
        ),
        DevicePreset(
            id = "pixel_8",
            name = "Google Pixel 8 (Shiba)",
            model = "Pixel 8",
            brand = "Google",
            androidVersion = 14,
            chromeVersion = 124,
            screenWidth = 1080,
            screenHeight = 2400,
            screenDensity = 3.0f,
            gpu = "Mali-G715",
            cores = 8,
            ramGb = 8,
            tlsId = "HelloChrome_124",
            userAgent = "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36",
            clientHintsPlatform = "Android",
            clientHintsPlatformVersion = "14.0.0",
            clientHintsModel = "Pixel 8"
        ),
        DevicePreset(
            id = "galaxy_s22",
            name = "Samsung Galaxy S22",
            model = "SM-S901B",
            brand = "Samsung",
            androidVersion = 14,
            chromeVersion = 123,
            screenWidth = 1080,
            screenHeight = 2340,
            screenDensity = 3.0f,
            gpu = "Xclipse 920",
            cores = 8,
            ramGb = 8,
            tlsId = "HelloChrome_123",
            userAgent = "Mozilla/5.0 (Linux; Android 14; SM-S901B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36",
            clientHintsPlatform = "Android",
            clientHintsPlatformVersion = "14.0.0",
            clientHintsModel = "SM-S901B"
        )
    )

    fun getById(id: String): DevicePreset? = presets.find { it.id == id }
}
